language: node_js
node_js:
- '7'
deploy:
  provider: heroku
  api_key:
    secure: uIkXUX33sHSXnEHU29voGpEpZvyxTRCD/mlHoACdyCCE1n15M5sI74W3pdm7w7cZVkesc7EiepzIA7DVB5qQ5O2q4WpXaD2up+r7e3zjyXmffyfq7CJqF+BB58L3gtXN2Yi9C5osfexpiwh4LMX6VrOzu5kiNPaCcjAq2JhjmFMFniKudK/qoMbyyHnzKB1hCtMrglfTJ028Q1s3W+aEbahgQfzT9EuXyGivN4CaylthOH7Zpd5US5F39bwcWeeKLE5Kb1EH2h5tGrmnV5Z/5lPRz2HI662oRLIyPkNiRyOki/1No2z4X817QWTE49g82qKbkVmpBueMjOIAuueXml1dU8MNMZTrCKeYGlEbU4XM6WSNlPlXoYc0LF1E5D6KDQUtIeMRnqomG+5CQmD3mvie2sWOL91s28PaJD7bp5Y+OOTHfinVz13OSG3HHRrI09WgSI3Qa5af5DtWl/S3sltLidkJWNNwS48ugI7+NmTY2YY9QwHcKkjtJQ48k/8z9uwMvOAXW1Z8MPGGuzrUJ2E4wC/OHqaitA4ZYZ+je/AP/CN+9WZFe2N0ZzH7YmthZMwipzlemnwyAagR8KnXfJWliNyZr55EnkjmOuDQecrafbMDsa2lFjXR7LuKxeYUhE4SPiJpcOjNRAQ8N8aO35WsYzWQSUrx2EGcgVdzGQI=
  app: narwhal-pod-microservice
  on:
    repo: narwhal-chat/narwhal-pod-microservice
